# This is a basic workflow to help you get started with Actions we do
#test
name: Build & Test

on:
  push:
    paths:
    - 'apis/poi/**'

defaults:
  run:
    working-directory: ./apis/poi

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
    - name: Install dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration Release --no-restore
    - name: Test
      run: dotnet test --no-restore --verbosity normal
      
  
  acr_build:
    runs-on: ubuntu-latest
    steps:
    - name: ACR build
      id: acr
      uses: ams0/acr-task-github-action@v1
      with:
        service_principal: ${{ secrets.service_principal }}
        service_principal_password: ${{ secrets.service_principal_password }}
        tenant: ${{ secrets.tenant }}
        registry: ${{ secrets.registry }}
        repository: ${{ secrets.repository }}
        image: poi
        folder: apis/poi/web
        dockerfile: Dockerfile
  
  acr_deploy:
    runs-on: ubuntu-latest
    needs: acr_build
    steps:
    - name: ACR deploy
      uses: azure/webapps-deploy@v2
      with:
        service_principal: ${{ secrets.service_principal }}
        service_principal_password: ${{ secrets.service_principal_password }}
        tenant: ${{ secrets.tenant }}
        registry: ${{ secrets.registry }}
        repository: ${{ secrets.repository }}  
        app-name: 'vijaypoiwebapp'
        images: ${{ secrets.registry }}/ ${{ secrets.repository }}:latest
